* IDS Editing Tool for Emacs

This file provides various IDS (Ideographic Description Sequence)
editing tools for Emacs. The IDS represents a structure of
Ideographs. For example, "地" can be decomposed to "⿰土也" in IDS,
and "⿱艹化" can be composed to "花".  "⿰" and "⿱" are called IDCs
(Ideographic Description Characters).

** Basic setup

Please BYTE-COMPILE the elisp file. That will integrate data files
into compiled lisp file.

: (autoload 'ids-edit "ids-edit" nil t) ;; if necessary
: (global-set-key (kbd "M-U") 'ids-edit) ;; sample keybinding.

** Decomposing CJK Ideographs to IDS

Just `M-x ids-edit' after the CJK Ideographs. There should be no
numerics, ideographs or IDCs at the cursor.

** Composing IDS to CJK Ideograph

Just `M-x ids-edit' on partial IDS. It may contain a (range of)
strokes number. When there are multiple candidates, they will all be
inserted to the current position with bracket. Attaching G,T,J,K at
the end will limit the candidates to specific charset (namely, GB2312,
Big5, JISX0213/0212, KSX1011).

For example, "⿰氵20-22J" will be composed to "[灊灝灞灣]".

** "ids-edit" Minor Mode

This mode lets you type IDC easily, by binding them to M-0 ... M-9,
M-=, M-- keys.

** Data Sources

Data 'ids.txt' and 'ucs-strokes.txt' are taken from
http://github.com/cjkvi/. License follows their terms.
